FROM amazoncorretto:17-alpine-jdk AS builder
LABEL authors="jaewonLeeKOR"

#작업 디렉토리를 /app으로 설정
WORKDIR /app

COPY gradlew build.gradle settings.gradle ./
COPY gradle ./gradle
COPY src ./src
COPY config ./config

RUN ./gradlew bootJar

FROM amazoncorretto:17-alpine-jdk
LABEL authors="jaewonLeeKOR"

WORKDIR /app

COPY --from=builder /app/build/libs/*.jar /app/app.jar

EXPOSE 8080

ENTRYPOINT java -jar /app/app.jar